// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TheaterLaakBackend.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EmailWordtVerzondenNaarDeGebruikerNadatHijEenAccountHeeftAangemaaktZodatHijZijnEmailKanValiderenFeature : object, Xunit.IClassFixture<EmailWordtVerzondenNaarDeGebruikerNadatHijEenAccountHeeftAangemaaktZodatHijZijnEmailKanValiderenFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MailSenderTest.feature"
#line hidden
        
        public EmailWordtVerzondenNaarDeGebruikerNadatHijEenAccountHeeftAangemaaktZodatHijZijnEmailKanValiderenFeature(EmailWordtVerzondenNaarDeGebruikerNadatHijEenAccountHeeftAangemaaktZodatHijZijnEmailKanValiderenFeature.FixtureData fixtureData, TheaterLaakBackend_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Email wordt verzonden naar de gebruiker nadat hij een account heeft aangemaakt zo" +
                    "dat hij zijn email kan valideren", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Send email successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "Email wordt verzonden naar de gebruiker nadat hij een account heeft aangemaakt zo" +
            "dat hij zijn email kan valideren")]
        [Xunit.TraitAttribute("Description", "Send email successfully")]
        public void SendEmailSuccessfully()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Send email successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 2
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
testRunner.Given("the email address \"theaterlaak123@gmail.com\" and subject \"test email!\" and text \"" +
                        "dit is een test email negeer deze!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
testRunner.When("the sendMail method is called with the given email address, subject, and text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
testRunner.Then("a message should have been sent to the user and the method returned true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                EmailWordtVerzondenNaarDeGebruikerNadatHijEenAccountHeeftAangemaaktZodatHijZijnEmailKanValiderenFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                EmailWordtVerzondenNaarDeGebruikerNadatHijEenAccountHeeftAangemaaktZodatHijZijnEmailKanValiderenFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
